name: CI

on:
    pull_request:
        branches: [develop]
    push:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: "12.x"
            - run: npm ci
            - run: npm run format 
            - run: npm run format:check
            - run: npm test -- --coverage
              env:
                  CI: true
            - name: Build Project
              if: github.event_name == 'push'
              run: npm run build
            - run: npm install -g surge
            - name: Deploy to Staging via surge
              if: github.event_name == 'push'
              run: surge --project ./build --domain longing-pull.surge.sh
              env:
                SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
                SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
